// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieProject.Data;

namespace MovieProject.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210531143454_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieProject.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Bilim Kurgu"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Aksiyon"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Komedi"
                        });
                });

            modelBuilder.Entity("MovieProject.Core.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("InnerBarkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfHalls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Beylikdüzü / İstanbul",
                            Capacity = 250,
                            IsDeleted = false,
                            Name = "Beylikdüzü Sinema Salonu",
                            NumberOfHalls = 5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Beykoz / İstanbul",
                            Capacity = 500,
                            IsDeleted = false,
                            Name = "Beykoz Sinema Salonu",
                            NumberOfHalls = 10
                        });
                });

            modelBuilder.Entity("MovieProject.Core.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InnerBarkod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "1.jpg",
                            IsDeleted = false,
                            Name = "7.Koğuştaki Mucize",
                            Subject = "Yedinci Koğuştaki Mucize, 7 yaşındaki kızı ile aynı zeka yaşına sahip bir babanın adalet arayışını konu ediyor. 1983 yılında bir Ege kasabasında küçük bir kız ölür. Ölen küçük kız sıkıyönetim komutanının kızıdır ve onun ölümünün sorumlusu olarak babaannesi ile yaşayan ve 7 yaşında bir kızı olan Memo görülür.",
                            Time = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "2.jpg",
                            IsDeleted = false,
                            Name = "Esaretin Bedeli",
                            Subject = "Stephen King'in Rita Hayworth ve Shawshank'in Kefareti adlı novellasından uyarlanan film, masumiyetini iddia etmesine rağmen karısını ve sevgilisini öldürdüğü gerekçesiyle Shawshank Devlet Cezaevi'nde yaklaşık 20 yılını geçiren bankacı Andy Dufresne'in hikâyesini anlatır.",
                            Time = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ImageUrl = "3.jpg",
                            IsDeleted = false,
                            Name = "The Platform",
                            Subject = "The Platform filmi, Her katında sadece iki kişinin bulunduğu ve çok katlı olan bir hapishanede yaşanılan sınıfsal ayrımları ve haksızlıkları anlatıyor. Hapishanede dağıtılan yemekler ilk başta en üst katta olanlara veriliyor, artan yemekler ise bir alt kattakine gidiyor.",
                            Time = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            ImageUrl = "4.jpg",
                            IsDeleted = false,
                            Name = "Extraction",
                            Subject = "Extraction, silah satıcıları ve kaçakçılara ait bir dünyada, uyuşturucu lordları arasında geçen savaşta piyon olan genç bir çocuğun hikayesini konu ediliyor. Kaçırılıp, dünyanın en ücra şehrine gönderilen Hintli çocuğun işadamı olan babası, oğlunu kurtarması için bir adam kiralar.",
                            Time = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            ImageUrl = "5.jpg",
                            IsDeleted = false,
                            Name = "Aykut Enişte",
                            Subject = "Aykut Enişte, yalnızlığından şikayetçi olan ve aile özlemi çeken bir adam olan Aykut'un hikayesini konu ediyor. Aykut, evlenip yuva kurmanın hayali ile yaşayan genç bir adamdır. ... Dükkana bakmak için sigortadan gelen Gülşah'ın, Aykut'tan küçük bir iyilik istemesi hepsinin hayatının değişmesine neden olur.",
                            Time = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            ImageUrl = "6.jpg",
                            IsDeleted = false,
                            Name = "Kolpaçino",
                            Subject = "Tayfun, İstanbul'un ünlü suç adamlarından Ateş'in yanında çalışmaktadır. Kendisinden mal çaldığını düşünen Ateş, Tayfun'u 10 gün içinde eksilen mallarını geri getirmek ve 50 bin dolarla cezalandırır. Tayfun bu parayı bulmak için Dolapdereli Sabri'den yardım ister.",
                            Time = 2
                        });
                });

            modelBuilder.Entity("MovieProject.Core.Models.Movie", b =>
                {
                    b.HasOne("MovieProject.Core.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieProject.Core.Models.Cinema", null)
                        .WithMany("Movies")
                        .HasForeignKey("CinemaId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MovieProject.Core.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieProject.Core.Models.Cinema", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
